In [ ]:
import numpy as np

# Define the grid world environment
# S: Start, G: Goal, x: Obstacle
# Actions: 0 - Up, 1 - Right, 2 - Down, 3 - Left
grid_world = np.array([
    ['S', ' ', 'x', ' '],
    [' ', 'x', ' ', ' '],
    [' ', ' ', ' ', 'G']
])

# Define rewards for each state
rewards = {
    'S': 0,
    ' ': 0,
    'x': -10,  # Penalty for hitting an obstacle
    'G': 100   # Reward for reaching the goal
}

# Define parameters
gamma = 0.9  # Discount factor
alpha = 0.1  # Learning rate
epsilon = 0.1  # Epsilon-greedy exploration parameter

# Initialize Q-values
num_actions = 4
num_states = np.prod(grid_world.shape)
Q = np.zeros((num_states, num_actions))

# Convert grid world to state indices
def state_to_index(state):
    return np.ravel_multi_index(state, grid_world.shape)

# Convert state index to grid world coordinates
def index_to_state(index):
    return np.unravel_index(index, grid_world.shape)

# Perform Q-learning with Temporal Difference
num_episodes = 1000
for episode in range(num_episodes):
    state = (0, 0)  # Starting state
    while True:
        # Epsilon-greedy action selection
        if np.random.rand() < epsilon:
            action = np.random.randint(num_actions)
        else:
            action = np.argmax(Q[state_to_index(state)])

        # Take action and observe next state and reward
        if action == 0:  # Up
            next_state = (max(state[0] - 1, 0), state[1])
        elif action == 1:  # Right
            next_state = (state[0], min(state[1] + 1, grid_world.shape[1] - 1))
        elif action == 2:  # Down
            next_state = (min(state[0] + 1, grid_world.shape[0] - 1), state[1])
        else:  # Left
            next_state = (state[0], max(state[1] - 1, 0))

        reward = rewards[grid_world[next_state]]

        # Update Q-value using Temporal Difference
        next_index = state_to_index(next_state)
        Q[state_to_index(state), action] += alpha * (
            reward + gamma * np.max(Q[next_index]) - Q[state_to_index(state), action])

        state = next_state

        if grid_world[state] == 'G':
            break

# Print the learned Q-values
print("Learned Q-values:")
print(Q)

# Find the optimal policy
optimal_policy = np.argmax(Q, axis=1).reshape(grid_world.shape)
print("\nOptimal Policy (0: Up, 1: Right, 2: Down, 3: Left):")
print(optimal_policy)


Learned Q-values:
[[ 47.37624218  56.61        39.76268723  46.56115662]
 [ 54.83962283  62.9         33.15197359  47.27387508]
 [ 59.31918624  81.          63.62673637  53.54859132]
 [ 75.18135278  75.53029123  90.          56.7061653 ]
 [ 49.6571471   -1.9          0.           0.41298285]
 [ 54.62022395   9.04343537   0.           4.38851122]
 [  5.39        89.02477331   0.           4.90118849]
 [ 65.30221279  82.0232944  100.          67.44085168]
 [  0.           0.           0.           0.        ]
 [  2.27640755   0.           0.           0.        ]
 [  6.74155255   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]

Optimal Policy (0: Up, 1: Right, 2: Down, 3: Left):
[[1 1 1 2]
 [0 0 1 2]
 [0 0 0 0]]
